### ISSUE TITLE
how to start a personal blog as life log?

### ISSUE THREAD

**Issue by emenvoid** [emenzero/1#8]
should I reuse this repo?
: issues for todos, blogs for dones

should I use docsify?
: should use at the beginning, so I can focus on content instead of tools

what should I write?
: experience, what have I done and how I have done it

what shouldn't I write?
: knowledge, which should be written as books

**Comment by emenzero** [comment]
finish the first blog

**Comment by emenvoid** [comment]
changed Github Pages to Netlify, seems great
[Netlify: All-in-one platform for automating modern web projects.](https://www.netlify.com/)

**Comment by emenvoid** [comment]
finished first lifelog and setup with docsify+Netlify on my custom domain.
